import { mkdir, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, normalize } from "node:path";

import {
  CdkImportMapDocumentSchema,
  CdkResourceMappingSchema,
  GeneratedCfnTemplateSchema,
  type CdkImportMapDocument,
  type CdkResourceMapping,
  type GeneratedCfnTemplate,
  type ImportMapResource,
} from "./schemas.js";
import type { GeneratedProjectFile } from "./typescript-project.js";
import { coreMessages } from "../messages.js";

export interface WriteGeneratedCfnTemplateFileInput {
  readonly document: GeneratedCfnTemplate;
  readonly outputPath: string;
}

export interface WriteCdkImportMapFileInput {
  readonly document: CdkResourceMapping;
  readonly outputPath: string;
}

export interface WriteCdkImportReviewFileInput {
  readonly document: CdkImportMapDocument;
  readonly outputPath: string;
}

export interface WriteImportGuideFileInput {
  readonly document: CdkImportMapDocument;
  readonly outputPath: string;
}

export interface WriteGeneratedProjectFilesInput {
  readonly files: readonly GeneratedProjectFile[];
  readonly outputDirectory: string;
}

export async function writeGeneratedCfnTemplateFile(
  input: WriteGeneratedCfnTemplateFileInput,
): Promise<void> {
  await mkdir(dirname(input.outputPath), { recursive: true });
  await writeFile(
    input.outputPath,
    formatGeneratedCfnTemplate(input.document),
    {
      encoding: "utf8",
    },
  );
}

export async function writeCdkImportMapFile(
  input: WriteCdkImportMapFileInput,
): Promise<void> {
  await mkdir(dirname(input.outputPath), { recursive: true });
  await writeFile(input.outputPath, formatCdkImportMap(input.document), {
    encoding: "utf8",
  });
}

export async function writeCdkImportReviewFile(
  input: WriteCdkImportReviewFileInput,
): Promise<void> {
  await mkdir(dirname(input.outputPath), { recursive: true });
  await writeFile(input.outputPath, formatCdkImportReview(input.document), {
    encoding: "utf8",
  });
}

export async function writeImportGuideFile(
  input: WriteImportGuideFileInput,
): Promise<void> {
  await mkdir(dirname(input.outputPath), { recursive: true });
  await writeFile(input.outputPath, formatImportGuide(input.document), {
    encoding: "utf8",
  });
}

export async function writeGeneratedProjectFiles(
  input: WriteGeneratedProjectFilesInput,
): Promise<void> {
  for (const file of [...input.files].sort((left, right) =>
    left.path.localeCompare(right.path),
  )) {
    const relativePath = safeRelativePath(file.path);
    const outputPath = join(input.outputDirectory, relativePath);
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, file.contents, { encoding: "utf8" });
  }
}

export function formatGeneratedCfnTemplate(
  document: GeneratedCfnTemplate,
): string {
  return `${JSON.stringify(GeneratedCfnTemplateSchema.parse(document), null, 2)}\n`;
}

export function formatCdkImportMap(document: CdkResourceMapping): string {
  return `${JSON.stringify(CdkResourceMappingSchema.parse(document), null, 2)}\n`;
}

export function formatCdkImportReview(document: CdkImportMapDocument): string {
  return `${JSON.stringify(CdkImportMapDocumentSchema.parse(document), null, 2)}\n`;
}

export function formatImportGuide(document: CdkImportMapDocument): string {
  const parsed = CdkImportMapDocumentSchema.parse(document);
  const ready = parsed.resources.filter(
    (resource) => resource.status === "ready",
  );
  const needsReview = parsed.resources.filter(
    (resource) => resource.status === "needs-review",
  );
  const blocked = parsed.resources.filter(
    (resource) => resource.status === "blocked",
  );
  const multipleStacks =
    (parsed.plan?.stacks.length ?? 0) > 1 &&
    !parsed.plan?.stacks.some((stack) => stack.stackName === parsed.stackName);
  const currentStack = parsed.plan?.stacks.find(
    (stack) => stack.stackName === parsed.stackName,
  );
  const mappingPath =
    currentStack && (parsed.plan?.stacks.length ?? 0) > 1
      ? `stacks/${currentStack.fileBase}/cdk-import-map.json`
      : "cdk-import-map.json";

  return `${[
    "# Import Guide",
    "",
    "This file was generated by cdk-excavator. Review every resource before running cdk import.",
    "Only resources marked ready are included in cdk-import-map.json. Review and manually add other mappings when safe.",
    "",
    "## Summary",
    "",
    `- Stack: ${parsed.stackName}`,
    `- Resources: ${parsed.resources.length}`,
    `- Ready: ${ready.length}`,
    `- Needs review: ${needsReview.length}`,
    `- Blocked: ${blocked.length}`,
    `- Boundary references: ${parsed.externalReferences.length}`,
    "",
    "## Required Safety Checks",
    "",
    "- Confirm the generated CDK template contains only new resources to import.",
    "- Run cdk diff before import and stop if unrelated updates or replacements appear.",
    "- Keep Retain policies on stateful resources before and after import.",
    "- Do not commit real account IDs, ARNs, or private resource names to a public repository.",
    "",
    "## Suggested Commands",
    "",
    coreMessages.t("core.generate.importCwd"),
    coreMessages.t("core.generate.importSetup"),
    "",
    "```bash",
    "npx cdk synth --no-lookups",
    ...(multipleStacks
      ? (parsed.plan?.stacks ?? []).map(
          (stack) => `npx cdk diff ${stack.stackName}`,
        )
      : [`npx cdk diff ${parsed.stackName}`]),
    ...(multipleStacks
      ? (parsed.plan?.stacks ?? []).map(
          (stack) =>
            `npx cdk import ${stack.stackName} --resource-mapping stacks/${stack.fileBase}/cdk-import-map.json`,
        )
      : [
          `npx cdk import ${parsed.stackName} --resource-mapping ${mappingPath}`,
        ]),
    "```",
    "",
    "## Resource Mapping Review",
    "",
    ...parsed.resources.flatMap(formatImportResource),
    "## Boundary Reference Review",
    "",
    ...(parsed.externalReferences.length > 0
      ? parsed.externalReferences.flatMap((reference) => [
          `- ${reference.boundaryHandling}: ${reference.type}=${reference.value} referencedBy=${reference.referencedByLogicalId ?? reference.referencedBy}`,
        ])
      : ["- None"]),
  ].join("\n")}\n`;
}

function formatImportResource(resource: ImportMapResource): string[] {
  return [
    `### ${resource.logicalId}`,
    "",
    `- Status: ${resource.status}`,
    `- CDK path: ${resource.cdkPath}`,
    `- Resource type: ${resource.resourceType}`,
    `- Physical identifier: ${resource.identifier}`,
    `- Import identifiers: ${formatImportIdentifiers(resource.importIdentifiers)}`,
    `- Review reasons: ${resource.reviewReasons.length > 0 ? resource.reviewReasons.join(", ") : "-"}`,
    "",
  ];
}

function formatImportIdentifiers(
  identifiers: Readonly<Record<string, string>>,
): string {
  const entries = Object.entries(identifiers).sort(([left], [right]) =>
    left.localeCompare(right),
  );

  return entries.length > 0
    ? entries.map(([key, value]) => `${key}=${value}`).join(", ")
    : "-";
}

function safeRelativePath(path: string): string {
  const normalized = normalize(path);

  if (
    isAbsolute(path) ||
    normalized === ".." ||
    normalized.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`)
  ) {
    throw new Error(`Generated project path must stay inside output: ${path}`);
  }

  return normalized;
}
